### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by abrez2004** [AlphaAtlas/VapourSynthColab#6]

**Comment by abrez2004** [comment]
/
HTesting script...
  File "<string>", line 1
    {'Script evaluation failed:', 'Python exception': 'knlm.KNLMeansCL': '8192x8192 is the highest resolution supported!', '', 'Traceback (most recent call last):', '  File "src\\cython\\vapoursynth.pyx", line 2244, in vapoursynth.vpy_evaluateScript', '  File "src\\cython\\vapoursynth.pyx", line 2245, in vapoursynth.vpy_evaluateScript', '  File "/content/autogenerated.vpy", line 63, in <module>', '    clip = core.knlm.KNLMeansCL(clip, a = 7, d = 3, h = 1.4)', '  File "src\\cython\\vapoursynth.pyx", line 2069, in vapoursynth.Function.__call__', 'vapoursynth.Error': 'knlm.KNLMeansCL': '8192x8192 is the highest resolution supported!', ''}
                                                    ^
SyntaxError: invalid syntax
